#!/usr/bin/env python3
"""Generate a native dispatch C++ file from a contract's ABI.

Reads the ABI JSON to extract action names, then emits a .cpp file with
an extern "C" apply() function that dispatches to the contract class methods.

Unlike SYSIO_DISPATCH, this generator:
  - Has no action count limit (SYSIO_DISPATCH is limited to ~32 by PP macros)
  - Supports non-void action return types (return value is discarded)
  - Supports actions spread across multiple classes (e.g. sysio.system)

Usage:
  python3 gen_native_dispatch.py --abi sysio.bios.abi \
    --contract-class "sysiobios::bios" --header "sysio.bios.hpp" \
    -o sysio.bios.native_dispatch.cpp

  # For contracts with actions on separate classes:
  python3 gen_native_dispatch.py --abi sysio.system.abi \
    --contract-class "sysiosystem::system_contract" \
    --header "sysio.system/sysio.system.hpp" \
    --extra-dispatch "sysiosystem::peer_keys:regpeerkey,delpeerkey,getpeerkeys" \
    --extra-dispatch "sysiosystem::trx_priority:addtrxp,deltrxp" \
    -o sysio.system.native_dispatch.cpp
"""

import json
import sys
import argparse


def parse_extra_dispatch(specs):
    """Parse --extra-dispatch CLASS:action1,action2,... into a dict of action -> class.

    The class may contain :: (e.g. sysiosystem::peer_keys), so we split on the
    LAST colon to separate the class from the action list.
    """
    action_to_class = {}
    if not specs:
        return action_to_class
    for spec in specs:
        if ':' not in spec:
            print(f"Error: --extra-dispatch format is CLASS:action1,action2,...  got: {spec}",
                  file=sys.stderr)
            sys.exit(1)
        idx = spec.rfind(':')
        cls = spec[:idx]
        actions_str = spec[idx + 1:]
        for action in actions_str.split(','):
            action = action.strip()
            if action:
                action_to_class[action] = cls
    return action_to_class


def main():
    parser = argparse.ArgumentParser(
        description='Generate native dispatch C++ from contract ABI')
    parser.add_argument('--abi', required=True,
                        help='Path to the contract .abi JSON file')
    parser.add_argument('--contract-class', required=True,
                        help='Fully qualified C++ class (e.g. "sysiobios::bios")')
    parser.add_argument('--header', required=True, action='append',
                        help='Contract header to #include (can be repeated)')
    parser.add_argument('--extra-dispatch', action='append', default=[],
                        help='Route actions to a different class: CLASS:action1,action2,...')
    parser.add_argument('-o', '--output', required=True,
                        help='Output .cpp file path')
    args = parser.parse_args()

    with open(args.abi, 'r') as f:
        abi = json.load(f)

    actions = [a['name'] for a in abi.get('actions', [])]
    if not actions:
        print(f"Error: no actions found in {args.abi}", file=sys.stderr)
        sys.exit(1)

    default_cls = args.contract_class
    overrides = parse_extra_dispatch(args.extra_dispatch)

    # Generate switch cases for each action
    cases = []
    for action in sorted(actions):
        cls = overrides.get(action, default_cls)
        cases.append(
            f'         case sysio::name("{action}").value:\n'
            f'            sysio::execute_action(sysio::name(receiver), sysio::name(code), &{cls}::{action});\n'
            f'            break;'
        )
    case_block = '\n'.join(cases)

    includes = '\n'.join(f'#include "{h}"' for h in args.header)

    content = (
        '// Auto-generated by gen_native_dispatch.py — do not edit.\n'
        '// Native dispatch wrapper: provides the apply() entry point that\n'
        '// sysio_codegen would normally generate during WASM compilation.\n'
        '\n'
        f'{includes}\n'
        '#include <sysio/dispatcher.hpp>\n'
        '#include <sysio/action.h>\n'
        '\n'
        '// Variant of execute_action that supports non-void return types.\n'
        '// Packs the return value and calls set_action_return_value, matching\n'
        '// the behavior of CDT\'s codegen-generated dispatch.\n'
        'namespace sysio {\n'
        '   template<typename T, typename R, typename... Args>\n'
        '   bool execute_action(name self, name code, R (T::*func)(Args...)) {\n'
        '      size_t size = action_data_size();\n'
        '      constexpr size_t max_stack_buffer_size = 512;\n'
        '      void* buffer = nullptr;\n'
        '      if (size > 0) {\n'
        '         buffer = max_stack_buffer_size < size ? malloc(size) : alloca(size);\n'
        '         read_action_data(buffer, size);\n'
        '      }\n'
        '      std::tuple<std::decay_t<Args>...> args;\n'
        '      datastream<const char*> ds((char*)buffer, size);\n'
        '      ds >> args;\n'
        '      T inst(self, code, ds);\n'
        '      if constexpr (std::is_void_v<R>) {\n'
        '         std::apply([&](auto&&... a) { ((&inst)->*func)(a...); }, args);\n'
        '      } else {\n'
        '         auto rv = std::apply([&](auto&&... a) { return ((&inst)->*func)(a...); }, args);\n'
        '         auto packed = pack(rv);\n'
        '         ::set_action_return_value(packed.data(), packed.size());\n'
        '      }\n'
        '      if (max_stack_buffer_size < size) free(buffer);\n'
        '      return true;\n'
        '   }\n'
        '}\n'
        '\n'
        'extern "C" {\n'
        '   [[sysio::wasm_entry]]\n'
        '   void apply(uint64_t receiver, uint64_t code, uint64_t action) {\n'
        '      if (code == receiver) {\n'
        '         switch (action) {\n'
        f'{case_block}\n'
        '         }\n'
        '      }\n'
        '   }\n'
        '}\n'
    )

    with open(args.output, 'w') as f:
        f.write(content)


if __name__ == '__main__':
    main()
