include(ExternalProject)
find_package(Git REQUIRED)
include(GNUInstallDirs)

ExternalProject_Add(
  CDTWasmLibraries
  SOURCE_DIR "${CMAKE_SOURCE_DIR}/libraries"
  BINARY_DIR "${CMAKE_BINARY_DIR}/libraries"
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE=${LIBS_BUILD_TYPE}
    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_BINARY_DIR}/lib/cmake/cdt/CDTWasmToolchain.cmake
    -DCDT_BIN=${CMAKE_BINARY_DIR}/lib/cmake/cdt/
    -DBASE_BINARY_DIR=${CMAKE_BINARY_DIR}
    -D__APPLE=${APPLE}
    -DENABLE_NATIVE_COMPILER=${ENABLE_NATIVE_COMPILER}
    -DCDT_INTERNAL_LIBRARY_BUILD=ON
    -DCDT_ALLOW_COMPILER_LAUNCHER=${CDT_ALLOW_COMPILER_LAUNCHER}
    -DCDT_NATIVE_CCACHE_DIR=${CDT_NATIVE_CCACHE_DIR}
    -DCDT_CCACHE_COMPILER_CHECK=${CDT_CCACHE_COMPILER_CHECK}
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    -DCMAKE_C_COMPILER_LAUNCHER=${CMAKE_C_COMPILER_LAUNCHER}
    -DCMAKE_CXX_COMPILER_LAUNCHER=${CMAKE_CXX_COMPILER_LAUNCHER}
    -DCMAKE_ASM_COMPILER_LAUNCHER=${CMAKE_ASM_COMPILER_LAUNCHER}
  UPDATE_COMMAND ""
  PATCH_COMMAND  ""
  TEST_COMMAND   ""
  INSTALL_COMMAND ""
  BUILD_ALWAYS 1
  DEPENDS CDTTools
)
