#!/bin/bash
# Regression test for cdt-ld's link-time ABI/dispatch finalize across MULTIPLE source subdirectories.
#
# `multidir_contract` is built (by the CDTWasmTests sub-build) from two .cpp files in two different
# subdirectories -- multidir/part_a/ and multidir/part_b/ -- each defining one action. CMake mirrors
# that layout under CMakeFiles/multidir_contract.dir/, so each object's finalize sidecar is written
# in a different directory. The dispatcher output path recorded in those sidecars must be derived
# from a TARGET-level location (the .abi directory); deriving it from each object's own directory
# makes the two sidecars disagree, and cdt-ld then aborts the link. In that regressed state this
# contract never links, so the main build fails before this test even runs. When it does link, this
# test additionally asserts the merged ABI contains BOTH subdirectories' actions -- i.e. descriptors
# from every source subdirectory were collected and merged.
#
# Usage: multidir_contract_tests.sh <build_dir>
set -euo pipefail

BUILD_DIR="$1"
CONTRACTS_DIR="${BUILD_DIR}/tests/unit/test_contracts"
ABI="${CONTRACTS_DIR}/multidir_contract.abi"
WASM="${CONTRACTS_DIR}/multidir_contract.wasm"
PASS=0
FAIL=0

pass() { echo "  PASS: $1"; PASS=$((PASS + 1)); }
fail() { echo "  FAIL: $1"; FAIL=$((FAIL + 1)); }

check_exists() {
    local desc="$1" file="$2"
    if [ -f "$file" ]; then pass "$desc"; else fail "$desc (missing: $file)"; fi
}

check_pattern() {
    local desc="$1" file="$2" pattern="$3"
    if [ -f "$file" ] && grep -q "$pattern" "$file"; then
        pass "$desc"
    else
        fail "$desc"
        echo "    expected pattern: $pattern"
        echo "    in file: $file"
    fi
}

echo "=== Multi-subdirectory contract finalize tests ==="

# The wasm exists only if cdt-ld's link-time finalize did NOT abort on a dispatch_output disagreement.
check_exists "wasm linked (link-time finalize did not abort)" "$WASM"

# The ABI was generated by the single finalize pass and must merge descriptors from both subdirs.
check_exists "abi generated" "$ABI"
check_pattern "action 'seta' present (defined in multidir/part_a/)" "$ABI" '"name": "seta"'
check_pattern "action 'setb' present (defined in multidir/part_b/)" "$ABI" '"name": "setb"'

echo ""
echo "Results: ${PASS} passed, ${FAIL} failed"
[ "$FAIL" -eq 0 ]
